import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <div className="flex flex-col">
      {data?.map((fullPost) => fullPost.content)}
    </div>
  );
};

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { isSignedIn, user } = useUser();
  console.log(user);

  return (
    <>
      <Head>
        <title>Visagebook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!isSignedIn && (
          <div className="flex flex-col content-center items-center justify-center">
            <h1 className="m-8 text-2xl">Not authenticated</h1>
            <SignIn />
          </div>
        )}
        {isSignedIn && (
          <div className="flex flex-col content-center items-center justify-center">
            <h1 className="m-8 text-2xl">Authenticated!</h1>
            <Feed />
            <SignOutButton />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
